CREATE USER dev_user IDENTIFIED BY 12345;

GRANT CREATE SESSION TO dev_user;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO dev_user;

ALTER USER DEV_USER QUOTA UNLIMITED ON USERS;