version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: 12345  # Задайте пароль для SYS, SYSTEM, PDBADMIN
      ORACLE_DATABASE: XEPDB1            # Имя PDB (по умолчанию XEPDB1)
      ORACLE_CHARACTERSET: AL32UTF8       # Кодировка базы
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
    driver: local
